/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'PaisAlunos\'">' + entity + '</span>' + html;
	}
	var icons = {
		'i-add': '&#xe900;',
		'i-announcement': '&#xe901;',
		'i-archive': '&#xe902;',
		'i-arrow-down': '&#xe903;',
		'i-arrow-left': '&#xe904;',
		'i-arrow-right': '&#xe905;',
		'i-arrow-up': '&#xe906;',
		'i-ban': '&#xe907;',
		'i-bank-account': '&#xe908;',
		'i-bell': '&#xe909;',
		'i-block-quote': '&#xe90a;',
		'i-bold': '&#xe90b;',
		'i-bolt': '&#xe90c;',
		'i-book': '&#xe90d;',
		'i-bookmark': '&#xe90e;',
		'i-browser': '&#xe90f;',
		'i-bullet-list': '&#xe910;',
		'i-calendar': '&#xe911;',
		'i-camera': '&#xe912;',
		'i-cart': '&#xe913;',
		'i-check-mark': '&#xe914;',
		'i-chevron-down': '&#xe915;',
		'i-chevron-left': '&#xe916;',
		'i-chevron-right': '&#xe917;',
		'i-chevron-up': '&#xe918;',
		'i-clipboard': '&#xe919;',
		'i-clock': '&#xe91a;',
		'i-cloud': '&#xe91b;',
		'i-code': '&#xe91c;',
		'i-credit-card': '&#xe91d;',
		'i-desktop': '&#xe91e;',
		'i-dollar': '&#xe91f;',
		'i-dots-vertical': '&#xe920;',
		'i-dots-horizontal': '&#xe921;',
		'i-download': '&#xe922;',
		'i-drop': '&#xe923;',
		'i-dupliacte': '&#xe924;',
		'i-emoji': '&#xe925;',
		'i-englarge': '&#xe926;',
		'i-euro': '&#xe927;',
		'i-fast-forward': '&#xe928;',
		'i-file': '&#xe929;',
		'i-filters': '&#xe92a;',
		'i-flag': '&#xe92b;',
		'i-folder': '&#xe92c;',
		'i-fullscreen': '&#xe92d;',
		'i-gift': '&#xe92e;',
		'i-grid': '&#xe92f;',
		'i-hashtag': '&#xe930;',
		'i-heading': '&#xe931;',
		'i-heart': '&#xe932;',
		'i-help': '&#xe933;',
		'i-hide': '&#xe934;',
		'i-highlight': '&#xe935;',
		'i-home': '&#xe936;',
		'i-inbox': '&#xe937;',
		'i-indent-left': '&#xe938;',
		'i-indent-right': '&#xe939;',
		'i-info': '&#xe93a;',
		'i-italic': '&#xe93b;',
		'i-launch': '&#xe93c;',
		'i-link': '&#xe93d;',
		'i-live-chat': '&#xe93e;',
		'i-location': '&#xe93f;',
		'i-lock': '&#xe940;',
		'i-log-out': '&#xe941;',
		'i-mail': '&#xe942;',
		'i-mention': '&#xe943;',
		'i-menu': '&#xe944;',
		'i-message': '&#xe945;',
		'i-mic': '&#xe946;',
		'i-mobile': '&#xe947;',
		'i-moon': '&#xe948;',
		'i-music': '&#xe949;',
		'i-mute': '&#xe94a;',
		'i-paperclip': '&#xe94b;',
		'i-pencil': '&#xe94c;',
		'i-pie-chart': '&#xe94d;',
		'i-pilcrow': '&#xe94e;',
		'i-pin': '&#xe94f;',
		'i-play': '&#xe950;',
		'i-pound': '&#xe951;',
		'i-redo': '&#xe952;',
		'i-refresh': '&#xe953;',
		'i-remove': '&#xe954;',
		'i-rewind': '&#xe955;',
		'i-rss': '&#xe956;',
		'i-sale': '&#xe957;',
		'i-schedule': '&#xe958;',
		'i-search': '&#xe959;',
		'i-selector': '&#xe95a;',
		'i-send': '&#xe95b;',
		'i-settings': '&#xe95c;',
		'i-share': '&#xe95d;',
		'i-star': '&#xe95e;',
		'i-stars': '&#xe95f;',
		'i-stop': '&#xe960;',
		'i-strikethrough': '&#xe961;',
		'i-subtract': '&#xe962;',
		'i-success': '&#xe963;',
		'i-sun': '&#xe964;',
		'i-tablet': '&#xe965;',
		'i-text-centered': '&#xe966;',
		'i-text-justified': '&#xe967;',
		'i-text-left': '&#xe968;',
		'i-text-right': '&#xe969;',
		'i-thumbs-down': '&#xe96a;',
		'i-thumbs-up': '&#xe96b;',
		'i-ticket': '&#xe96c;',
		'i-trash': '&#xe96d;',
		'i-underline': '&#xe96e;',
		'i-undo': '&#xe96f;',
		'i-unlock': '&#xe970;',
		'i-upload': '&#xe971;',
		'i-user': '&#xe972;',
		'i-users': '&#xe973;',
		'i-video': '&#xe974;',
		'i-video-1': '&#xe975;',
		'i-video-off': '&#xe976;',
		'i-view': '&#xe977;',
		'i-volume': '&#xe978;',
		'i-warning': '&#xe979;',
		'i-yen': '&#xe97a;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/i-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
